
services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: autonomous-intelligence-backend
    restart: unless-stopped
    ports:
      - "8000:5000"  # Map container's 5000 to host's 8000
      - "6379:6379"  # Ray
      - "9998:9998"  # Tika
    volumes:
      - ./:/app
      - ./db:/app/db
      - ./models:/app/models
      - tika-data:/tmp  # Persist Tika server data
      - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    env_file:
      - .env
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - FLASK_DEBUG=1
      - PYTHONUNBUFFERED=1
      - PYTHONDONTWRITEBYTECODE=1
    depends_on:
      - db
    networks:
      -  autonomous-intelligence-network
    shm_size: '2.44gb'
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
  db:
    image: mysql:8.0
    container_name:  autonomous-intelligence-db
    restart: always
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ALLOW_EMPTY_PASSWORD=true
        - MYSQL_DATABASE=autonomous_intelligence
        - MYSQL_ROOT_USER=root
        - MYSQL_HOST=host.docker.internal
    volumes:
        - mysql-data:/var/lib/mysql
        - ./database/schema.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
        - autonomous-intelligence-network
      
networks:
  autonomous-intelligence-network:
    driver: bridge

volumes:
  tika-data:  # Volume for Tika server data
  mysql-data: 