site_name: Agento
site_url: https://docs.anote.ai
use_directory_urls: false
# repo_url: https://github.com/nv78/Anote-Cookbook

nav:
  - Home: privategpt/privategpt.md
  - Anote SDK:
    - Getting Started:
      - Overview: api-overview/setup.md
      - Installation (Private): privategpt/installation.md
      - Upload: api-overview/upload.md
      - Upload (Private): api-overview/upload-private.md
      - Fine Tune: api-overview/finetune.md
      - Chat: api-overview/chat.md
      - Predict: api-overview/predict.md
      - Evaluate: api-overview/evaluate.md
    - Capabilities:
      - Q&A from Edgar: api-qa/example1.md
      - Q&A from Uploaded Files: api-qa/example2.md
      - Q&A in Multiple Languages: api-qa/example3.md
      - Q&A with websites: api-qa/example4.md
      - Q&A with fine tuning: api-qa/example5.md
  - Anote 10-Ks:
    - 10-Ks Background: 10-ks/10ksbackground.md
    - 10-Ks Questions: 10-ks/10ksquestions.md
    - 10-Ks Decomposition: 10-ks/10ksdecomposition.md
    - 10-Ks Feedback: 10-ks/10ksfeedback.md
    - 10-Ks Solution: 10-ks/10kssolution.md
    - 10-Ks Impact: 10-ks/10ksimpact.md
  - Anote Fine Tuning:
    - Overview: api-prompting/overview.md
    - Baseline Models: api-prompting/example1.md
    - Supervised: api-prompting/example2.md
    - Supervised Methods: api-prompting/example3.md
    - Unsupervised: api-prompting/example4.md
    - RLHF: api-prompting/example5.md
    - Traditional RAG: api-prompting/example6.md
    - Enhanced RAG: api-prompting/example7.md
    - Evaluation: api-prompting/example8.md

extra:
  homepage: https://anote.ai
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/anote-ai/
    - icon: fontawesome/brands/medium
      link: https://anote-ai.medium.com/

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - tables

theme:
  name: material
  features:
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.copy
    - content.code.annotation
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
      primary: black
      accent: light blue
    - scheme: slate
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
      primary: black
      accent: light blue
  favicon: assets/logo.png
  logo: assets/logo.png


plugins:
  - search:
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_section_style: table
  - swagger-ui-tag:
      syntaxHighlightTheme: monokai
      tryItOutEnabled: false
      supportedSubmitMethods: []
