# config/config.yaml
agents:
  - name: SearchAgent
    class: agents.search_agent.SearchAgent
  - name: AnalysisAgent
    class: agents.analysis_agent.AnalysisAgent
  - name: CommunicationAgent
    class: agents.communication_agent.CommunicationAgent

tools:
  search_api: tools.search_api.SearchAPI
  language_model: lm.llm_service.LLMService

api_keys:
  openai: "your_openai_api_key_here"
