# config/tasks.yaml

research_task:
  description: >
    Conduct a thorough research about AI
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 10 bullet points of the most relevant information about AI
  agent: researcher

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledged report with the main topics, each with a full section of information.
  agent: reporting_analyst

write_poem:
  description: >
    Compose a poem based on the given theme.
  expected_output: >
    A creative and engaging poem in markdown format.
  agent: poem_writer
