# config/rbac.yaml
roles:
  admin:
    permissions:
      - "use_all_agents"
      - "manage_workflows"
  user:
    permissions:
      - "use_search"
      - "use_analysis"
    restricted_agents:
      - "CommunicationAgent"