name: Lint Backend (Python) + CodeQL

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'
      - 'backend/**'
  pull_request:
    paths:
      - 'frontend/**'
      - 'backend/**'

jobs:
  lint:
    name: Lint Backend Only
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # --- Frontend steps temporarily disabled ---
      # - name: Set up Node.js
      #   uses: actions/setup-node@v4
      #   with:
      #     node-version: '20'
      #
      # - name: Install frontend dependencies
      #   working-directory: frontend
      #   run: npm ci
      #
      # - name: Lint frontend with ESLint
      #   working-directory: frontend
      #   run: npm test 

      # Setup Python (Backend)
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python lint dependencies
        working-directory: backend
        run: 
          python -m pip install --upgrade pip
          pip install flake8

      - name: Lint backend with flake8
        working-directory: backend
        run: flake8 .
      - name: Test backend with pytest
        working-directory: backend
        run: pytest

  codeql:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [javascript, python]

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild project
        uses: github/codeql-action/autobuild@v3

      - name: Run CodeQL analysis
        uses: github/codeql-action/analyze@v3

